package de.hahn.dynamictable.model.adfbc.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 28 09:40:38 CET 2016
// ---------------------------------------------------------------------
public interface BDTAppModule extends ApplicationModule {
    void createDynaView(String sql);
}

